apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: staticsite-sample-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: staticsite-sample-web
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: nginx_http_requests_per_second
      target:
        type: AverageValue
        averageValue: "5"
